package ORM;
// Generated 18 nov. 2020 20:00:38 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String dni;
	private String nomEmp;
	private DatosProf datosProf;
	private Set asigProyectos = new HashSet(0);
	private Set empPlantillas = new HashSet(0);

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, DatosProf datosProf, Set asigProyectos, Set empPlantillas) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.datosProf = datosProf;
		this.asigProyectos = asigProyectos;
		this.empPlantillas = empPlantillas;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public DatosProf getDatosProf() {
		return this.datosProf;
	}

	public void setDatosProf(DatosProf datosProf) {
		this.datosProf = datosProf;
	}

	public Set getAsigProyectos() {
		return this.asigProyectos;
	}

	public void setAsigProyectos(Set asigProyectos) {
		this.asigProyectos = asigProyectos;
	}

	public Set getEmpPlantillas() {
		return this.empPlantillas;
	}

	public void setEmpPlantillas(Set empPlantillas) {
		this.empPlantillas = empPlantillas;
	}

}
