package ORM;
// Generated 18 nov. 2020 20:00:38 by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private Integer idProy;
	private EmpPlantilla empPlantilla;
	private String nomProy;
	private Date FInicio;
	private Date FFin;
	private Set asigProyectos = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(EmpPlantilla empPlantilla, String nomProy, Date FInicio) {
		this.empPlantilla = empPlantilla;
		this.nomProy = nomProy;
		this.FInicio = FInicio;
	}

	public Proyecto(EmpPlantilla empPlantilla, String nomProy, Date FInicio, Date FFin, Set asigProyectos) {
		this.empPlantilla = empPlantilla;
		this.nomProy = nomProy;
		this.FInicio = FInicio;
		this.FFin = FFin;
		this.asigProyectos = asigProyectos;
	}

	public Integer getIdProy() {
		return this.idProy;
	}

	public void setIdProy(Integer idProy) {
		this.idProy = idProy;
	}

	public EmpPlantilla getEmpPlantilla() {
		return this.empPlantilla;
	}

	public void setEmpPlantilla(EmpPlantilla empPlantilla) {
		this.empPlantilla = empPlantilla;
	}

	public String getNomProy() {
		return this.nomProy;
	}

	public void setNomProy(String nomProy) {
		this.nomProy = nomProy;
	}

	public Date getFInicio() {
		return this.FInicio;
	}

	public void setFInicio(Date FInicio) {
		this.FInicio = FInicio;
	}

	public Date getFFin() {
		return this.FFin;
	}

	public void setFFin(Date FFin) {
		this.FFin = FFin;
	}

	public Set getAsigProyectos() {
		return this.asigProyectos;
	}

	public void setAsigProyectos(Set asigProyectos) {
		this.asigProyectos = asigProyectos;
	}

}
